import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";  // Import Link for navigation
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* NAVBAR */}
        <nav style={{ padding: "15px", borderBottom: "1px solid #ddd" }}>
          <Link href="/" style={{ marginRight: "15px" }}>Home</Link>
          <Link href="/about">About</Link>  {/* Add About Page link */}
        </nav>

        {/* MAIN CONTENT */}
        <main style={{ padding: "20px" }}>
          {children}
        </main>

        {/* FOOTER */}
        <footer style={{ textAlign: "center", marginTop: "20px", padding: "10px", borderTop: "1px solid #ddd" }}>
          <p>© 2024 Senior Design Project</p>
        </footer>

      </body>
    </html>
  );
}
